### PR TITLE
support speaking answers with 'say' and multiline input

### PR DESCRIPTION
**Pull request by scottleibrand**
If you'd like me to pick out some but not all of these changes, LMK and I'd be happy to break them apart.

Using this and Apple Dictation (after installing the Spanish Language in Dictation under Keyboard Preferences), I am able to practice my spoken Spanish using `python3 ./revChatGPT.py say -v Paulina -r 200`.

### CODE REVIEW

**Review by acheong08 — CHANGES_REQUESTED** [review]
The `say` command is MacOS specific. I would like this to work on all platforms.

Multi-line input would be appreciated though.

**Comment by scottleibrand** [comment]
The way I implemented it (but haven't documented yet) is to require the user to specify the extra command they want run on each response on the command line. So if there is a similar command on other platforms, they'd provide that command and its desired arguments as arguments to revChatGPT.py instead of `say` and its arguments. And if someone wanted to run a command to dump the responses to a database or something, they could easily do that too.

**Comment by scottleibrand** [comment]
image

**Review by acheong08 — CHANGES_REQUESTED** [review]
If that is the case, the arguments such as `-r 400` shouldn't be hard coded. I think it would be better to allow users to define a custom processor via the config file. For example, under a processor key, allow the user to define a command which is run every time an output is returned.

**Comment by scottleibrand** [comment]
Ah, good point, yeah. I'll pull that part out for now, and then we can improve the UX later.

**Review by acheong08 — APPROVED** [review]
Looks good for temporary use

**Pull request merged**
