### PR TITLE
temporary solution for async in effective way

### PR DESCRIPTION
**Pull request by Harry-Jing**
The issue in #311 happed because the previous code use none-async function `refresh_session()` wich contain `asyncio.run()` into async function `get_chat_response()`, this cause nested use of asyncio.run

Here is temporary solution to fix

### CODE REVIEW

**Comment by Harry-Jing** [comment]
I can't test my code at the moment because ChatGPT has too many visitors. And I need to go to bed too.

**Comment by BLuFeNiX** [comment]
@Harry-Jing Why not just use `threading.current_thread() is threading.main_thread()` to check if you're running in a different thread?
Or even save `threading.current_thread().ident` (in `__main__`) to compare later, in case someone wants to run the module itself in a different thread?

just an idea, as I haven't looked to deeply into this problem, and there's probably a better fix

**Review by acheong08 — APPROVED** [review]
Temporary fix. Improvements will be made later

**Comment by mgpai22** [comment]
I get these errors with this commit:

```
RuntimeWarning: coroutine 'AsyncChatbot.get_cf_cookies' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
asyncio.run() cannot be called from a running event loop
```

**Comment by xdtxAM** [comment]
> I get these errors with this commit:
> 
> ```
> RuntimeWarning: coroutine 'AsyncChatbot.get_cf_cookies' was never awaited
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> asyncio.run() cannot be called from a running event loop
> ```

I am also getting the same error message, did you solve it? Mine is arm MacBook

**Comment by ngillespie1** [comment]
Same issue:

`C:\script\Media>"C:\python\3.7.9\python.exe" test.py
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    chatbot = Chatbot({
  File "C:\python\3.7.9\lib\site-packages\revChatGPT\revChatGPT.py", line 480, in __init__
    debug, request_timeout, captcha_solver, base_url, max_rollbacks))
  File "C:\python\3.7.9\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\python\3.7.9\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\python\3.7.9\lib\site-packages\revChatGPT\revChatGPT.py", line 111, in __init__
    await self.refresh_session()
  File "C:\python\3.7.9\lib\site-packages\revChatGPT\revChatGPT.py", line 483, in refresh_session
    return asyncio.run(super().refresh_session())
  File "C:\python\3.7.9\lib\asyncio\runners.py", line 34, in run
    "asyncio.run() cannot be called from a running event loop")
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'AsyncChatbot.refresh_session' was never awaited`

The code is simple

`
from revChatGPT.revChatGPT import Chatbot

# Do some config
...


chatbot = Chatbot({
   # This could be blank but the dict should be here
})

prompt = input("Enter Prompt: ")
message = chatbot.get_chat_response(prompt, output="text")
print(message)
`

**Pull request merged**
