### PR TITLE
Add asynchronous support

### LINKED ISSUE #14: Can you add async support?
The requeset need long time to resbonse, so async can solve this problem in some way
you can use the HTTPX for both synchronous and async.

### PR DESCRIPTION
**Pull request by A-kirami**
resolve #14

### CODE REVIEW

**Comment by Harry-Jing** [comment]
But if this is modified then only asynchronous is supported, some people may prefer to use it out of the box, so is it possible to separate the asynchronous part into a separate function

**Comment by acheong08** [comment]
> But if this is modified then only asynchronous is supported, some people may prefer to use it out of the box, so is it possible to separate the asynchronous part into a separate function

This is correct

**Review by acheong08 — CHANGES_REQUESTED** [review]
Make the return type conditional with text as default. Return a pointer or async if specified.

**Review by acheong08 — CHANGES_REQUESTED** [review]
Why was so much code overwritten? Can the pull request only include changes that are necessary?

**Comment by acheong08** [comment]
One way to do this is to use threading and channels. Start a thread for the stream. While the response is still streaming, parse each line and send it through the channel. Stop streaming when the 'Done' message is received

**Review by acheong08 — COMMENTED** [review]
There are multiple bits of Chinese in the interface. I will merge this to a branch and edit it there.

**Comment by A-kirami** [comment]
> Why was so much code overwritten? Can the pull request only include changes that are necessary?

Sorry, this is caused by automatic formatting.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/tree/async-dev

**Pull request closed without merging**
