### PR TITLE
Fix typo in `README.md`

### PR DESCRIPTION
**Pull request by code-yeongyu**
I struggled with executing the project due to the typo in the README.md. After reviewing the README, I found that 'revApiGPT' was incorrectly written and revised it to 'revChatGPT'. This change ensures that the code is correct and will properly execute the project. Thank you for your time and consideration.

### CODE REVIEW

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/blob/41acfe5a5ad46d13a0e8cf751fd9f89dc3237625/README.md?plain=1#L58-L76

**Comment by code-yeongyu** [comment]
i was mentioning about line 34, can I ask you why have closed my PR?

**Comment by acheong08** [comment]
Line 34 was for the API (There was a mistake there though. Will fix)

**Comment by acheong08** [comment]
It's just `revApiGPT`

**Comment by acheong08** [comment]
revApiGPT is for the HTTP API

**Pull request closed without merging**
