### PR TITLE
Fix to version mismatch?

### PR DESCRIPTION
**Pull request by NymdaFromSalad**
Version is 3.1.1 in setup.py

### CODE REVIEW

**Comment by NymdaFromSalad** [comment]
(And 3.1.0 in __version__ in `src/revChatGPT/__init__.py`)

**Comment by acheong08** [comment]
Don't need version in `src/revChatGPT/__init__.py`. Just deleted that.

**Comment by NymdaFromSalad** [comment]
I mean, it's in PEP, and is useful
(Or is it supposed to be included differently? When i tested, there was no __version__)

Well, anyway, sorry for that, shouldn't have added it in my pull
And sorry for mixing up your name - sleep deprived myself

**Comment by acheong08** [comment]
> I mean, it's in PEP, and is useful

It works without it. "If it ain't broke, don't fix it"

**Pull request closed without merging**
