### PR TITLE
Remove usage of bs4

### PR DESCRIPTION
**Pull request by bird**
This removes the dependency of bs4 and replaces it with regex equivalents. I've tested it all as working but this may be more prone to breaking if things update.

### CODE REVIEW

**Review by acheong08 — APPROVED** [review]
Looks good. I test in dev branch first

**Comment by acheong08** [comment]
@bird Do you mind testing the latest commit (Not from pip) to see if it works? I have tested for myself and it works

**Comment by bird** [comment]
> @bird Do you mind testing the latest commit (Not from pip) to see if it works? I have tested for myself and it works

Just tested the latest commit and it worked fine for me (from login to responding to prompts).

**Comment by acheong08** [comment]
Nice. Publishing release

**Pull request merged**
