### PR TITLE
More Automatic

### PR DESCRIPTION
**Pull request by CoolPlayLin**

### CODE REVIEW

**Review by acheong08 — APPROVED** [review]
thanks!

**Comment by CoolPlayLin** [comment]
wait

**Comment by CoolPlayLin** [comment]
do not merge!!!!!!!!!!!!!!!!!

**Comment by CoolPlayLin** [comment]
I found a bug

**Comment by acheong08** [comment]
yup. waiting for checks to pass

**Comment by acheong08** [comment]
btw I think I should make a dev branch for pull requests to go into so I can test properly on GitHub before merging to main

**Comment by acheong08** [comment]
How do I make it so that pull requests are automatically assigned to that branch?

**Comment by CoolPlayLin** [comment]
> How do I make it so that pull requests are automatically assigned to that branch?

Look at this [github-script](https://github.com/actions/github-script)

**Comment by CoolPlayLin** [comment]
@acheong08 
image

**Comment by CoolPlayLin** [comment]
@acheong08

**Pull request merged**
