### PR TITLE
Refactor the code, change a lot

### PR DESCRIPTION
**Pull request by Harry-Jing**
All the class name follow [pep-8](https://peps.python.org/pep-0008/#class-names), ChatBot AsyncChatBot
increases maintainability.

flaw:
__get_chat_text revert to earlier versions
the ChatBot get_chat_response( prompt, output="stream")return list, not a generator

### CODE REVIEW

**Comment by Harry-Jing** [comment]
if I update __get_chat_text() function, I'll got error

**Review by acheong08 — CHANGES_REQUESTED** [review]
Sorry about the text bug. It's fixed now. Mind going over it?

**Comment by Harry-Jing** [comment]
I update the #241 , bug still error

**Comment by Harry-Jing** [comment]
you can do some test to try it

**Comment by acheong08** [comment]
> I update the #241 , bug still error I have no idea about that

It was due to the error handling coming before the text splits. I just fixed it https://github.com/acheong08/ChatGPT/commit/c460ca8723a083d42db49157758129ca3cd5a3a1

**Comment by Harry-Jing** [comment]
I think there is no other problem

**Review by acheong08 — APPROVED** [review]
I'll merge and see if it gets fixed then

**Comment by Harry-Jing** [comment]
the doc also need to update

**Comment by acheong08** [comment]
I think `Chatbot` should remain rather than `ChatBot` as it is a single word.

**Comment by acheong08** [comment]
> the doc also need to update

I will do that

**Comment by acheong08** [comment]
@Harry-Jing No doc changes needed. I have tested it and it works. Releasing as new version

**Comment by Harry-Jing** [comment]
> @Harry-Jing I have tested it and it works. Releasing as new version 
> 
> 
> 
> Doc changes pending

But the class name change

**Comment by acheong08** [comment]
I reverted the class name changes. Chatbot is a single word. Not ChatBot

**Comment by Harry-Jing** [comment]
ok

**Pull request merged**
