### PR TITLE
even more improve exception

### PR DESCRIPTION
**Pull request by CoolPlayLin**
# view

image

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
@acheong08

**Review by acheong08 — APPROVED** [review]

**Review by acheong08 — APPROVED** [review]

**Comment by acheong08** [comment]
> @acheong08

Btw You don't need to ping me like that. All issue comments and pull requests get sent directly to my email. If I don't immediately review them, it means I am either at school, sleeping, or outside.

**Comment by CoolPlayLin** [comment]
> > @acheong08
> 
> Btw You don't need to ping me like that. All issue comments and pull requests get sent directly to my email. If I don't immediately review them, it means I am either at school, sleeping, or outside.

You are in China????????????

**Comment by CoolPlayLin** [comment]
You are in the same time zone as me

**Comment by acheong08** [comment]
> You are in China????????????

Yes

**Comment by CoolPlayLin** [comment]
所有你可以理解中文吧

**Comment by peanut996** [comment]
都是中国人吗 🤣

**Comment by CoolPlayLin** [comment]
> 都是中国人吗 🤣

作者是留学生 @peanut996

**Pull request merged**
