### PR TITLE
Use httpx for links instead of requests

### PR DESCRIPTION
**Pull request by Harry-Jing**
Compared to requests, httpx is a better choice, which provides sync and async APIs.
After this it will easy to add async support to this project.
async is really important to me. my native language is Chinese. This request takes a long time to wait than English, sometimes it takes 20-30 seconds and longer. And my bot also need async support to handle message better.

### CODE REVIEW

**Review by acheong08 — COMMENTED** [review]
Requests is a bit more native and I want to avoid messing up the authentication protocol. Will convert to draft and see if anyone is willing to maintain an httpx branch

**Comment by Harry-Jing** [comment]
httpx is very similar to requests,

**Comment by Harry-Jing** [comment]
httpx is very similar to requests, the codes are alomost same

**Comment by Harry-Jing** [comment]
You can also directly replace the content of requests with httpx directly. XD

**Comment by acheong08** [comment]
Using stream=True in requests is the same as async httpx

**Comment by acheong08** [comment]
Oh I see. Stream uses a generator rather than async

**Comment by acheong08** [comment]
@Harry-Jing Do you mind resolving the conflicts? I will test this and merge if possible

**Pull request closed without merging**
