### PR TITLE
fix bug when change to httpx

### PR DESCRIPTION
**Pull request by Harry-Jing**

### CODE REVIEW

**Comment by acheong08** [comment]
Conflicts require fixing.

**Comment by Harry-Jing** [comment]
how about now

**Comment by acheong08** [comment]
Code scanning in progress. I will merge once it passes

**Review by acheong08 — APPROVED** [review]
Approved

**Comment by Harry-Jing** [comment]
I believe there will be no more problems this time XD

**Comment by acheong08** [comment]
@Harry-Jing You forgot to add the import statement and the requirements in `setup.py`. Fixed though

**Comment by acheong08** [comment]
@Harry-Jing Forgot to implement for get_chat_text

**Comment by Harry-Jing** [comment]
the code have no problem, it was wrong when merging

**Comment by acheong08** [comment]
Ah. That was probably the issue. I kept updating the codebase due to other things that needed to be fixed which caused issues with the merge

**Comment by Harry-Jing** [comment]
image
So what should i do now

**Comment by acheong08** [comment]
Since httpx and requests are pretty much the same, I think this can be put off until later. Rather than changing everything to httpx, you can write a separate async class that extends the Chatbot class. Trying to change the way the whole thing works is too unstable.

**Pull request merged**
